name: Auto PR
on:
  push:
    branches: [dev]
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/create-pull-request@v5
        with:
          title: "Auto PR: dev → main"
          base: main
          head: dev
